### ISSUE TITLE
LdaCgsMulti on Windows

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/vsm#101]
Presently, LdaCgsMulti does not work on Windows due to the following error caused by [issues in multiprocessing with Windows](https://docs.python.org/2/library/multiprocessing.html#windows).

```python
Training model for k=10 Topics with 2 Processes
Traceback (most recent call last):                                            |
  File "train.py", line 162, in <module>
    n_iterations=args.iter, n_proc=args.processes)
  File "train.py", line 83, in build_models
    m.train(n_iterations=n_iterations, n_proc=n_proc)
  File "c:\users\jaimie\documents\vsm\vsm\model\ldacgsmulti.py", line 270, in train
    results = p.map(update, data)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 558, in get
    raise self._value
NameError: global name '_corpus' is not defined
```

I've committed a temporary patch, but if it is possible to load the objects in global memory. There is a [numpy-sharedmem package](http://stackoverflow.com/questions/5033799/how-do-i-pass-large-numpy-arrays-between-python-subprocesses-without-saving-to-d) that may help us here. 

I am also concerned about the use of global variables and thread safety, which should at least be documented if true.

**Comment by rrose1** [comment]
The issue with Windows is that it uses `spawn` instead of `fork`. From what I understand, the library you mention simply provides some facilities for moving between the shared memory structures provided by multiprocessing and numpy data structures (which I didn't find more useful than using the multiprocessing.Array and multiprocessing.Value and numpy.frombuffer directly). The problem to solve is how to pass references to the shared data structures down from the parent process in Windows.

Would you be more specific about what could go wrong thread-safety-wise? Also, do you know a technique for implementing data structure sharing without copying in Python (or Cython) that doesn't involve global references? It sounds like you want something beyond the functional scope of these fairly limited tools.

**Comment by rrose1** [comment]
I don't think the present patch is a good idea. Initializing LdaCgsMulti in Windows should return an exception and direct the user to use LdaCgsSeq.

**Comment by JaimieMurdock** [comment]
I'll change this to raise a "NotImplementedError" with a warning message 
for LdaCgsSeq.

Perhaps the workaround should be moved to the `__new__` method of LDA, 
avoiding the call of LdaCgsSeq or LdaCgsMulti directly.

**Comment by JaimieMurdock** [comment]
Added a better workaround in commit 75c5ce7d0bb496e1e121394a7baedcff30bb36a7.

**Comment by JaimieMurdock** [comment]
Closing issue. It is not implemented, but appropriate user interfaces have been developed.
