### ISSUE TITLE
vsm update and GitPython

### ISSUE THREAD

**Issue by colinallen** [inpho/vsm#124]
After updating to the latest version via pip, when I run vsm update, it tells me:
GitPython is required, but is not installed. Install? [Y/n] 

I’ve not done that because it all seems to work regardless. So, perhaps I don't really need GitPython. But if I do really need it, why doesn’t the pip process install it?

**Comment by JaimieMurdock** [comment]
This bug is for inpho/topic-explorer. Naming conventions need to change for topic-explorer so these issues stop.

The GitPython question is asked only on `vsm update` because you only need GitPython when you have a development install and are trying to update. If you are an end user, we don't need to require GitPython because you may not have `git` installed on your computer. The update process should have exited after answering `n`. If you answered `yes` or blank, it would have installed GitPython and continued with the update.
